export enum UsersMicroserviceMessages {
  USERS_MS_PING = `USERS_MS_PING`,

  CREATE_USER = `CREATE_USER`,
  UPDATE_USER = `UPDATE_USER`,
  DELETE_USER = `DELETE_USER`,
  DESTROY_USER = `DESTROY_USER`,

  GET_USER_BY_ID = `GET_USER_BY_ID`,
  GET_USER_BY_EMAIL = `GET_USER_BY_EMAIL`,
  GET_USER_BY_PHONE = `GET_USER_BY_PHONE`,
  QUERY_USERS = `QUERY_USERS`,

  USER_PASSWORD_UPDATE = `USER_PASSWORD_UPDATE`,
  USER_PASSWORD_RESET = `USER_PASSWORD_RESET`,

  SEND_EMAIL_VERIFICATION_CODE = `SEND_EMAIL_VERIFICATION_CODE`,
  SEND_PHONE_VERIFICATION_CODE = `SEND_PHONE_VERIFICATION_CODE`,

  EMAIL_VERIFICATION = `EMAIL_VERIFICATION`,
  PHONE_VERIFICATION = `PHONE_VERIFICATION`,
}

export enum UsersMicroserviceEvents {
  USERS_MS_PINGED = `USERS_MS_PINGED`,

  USER_CREATED = `USER_CREATED`,
  USER_UPDATED = `USER_UPDATED`,
  USER_DELETED = `USER_DELETED`,
  USER_DESTROYED = `USER_DESTROYED`,
}