version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: app-rabbitmq
    ports:
      - '5672:5672'

  web-api-gateway:
    build:
      context: .
      dockerfile: ./docker/nestjs-app.Dockerfile
      target: development
      args:
        NESTJS_APP: web-api-gateway
    ports:
      - '3000:80'
    env_file:
      - ./env/web-api-gateway.env
      - ./env/rabbitmq.env
    command: npm run start:dev web-api-gateway
    depends_on:
      - rabbitmq
    volumes:
        - .:/app
        - /app/node_modules

  mobile-api-gateway:
    build:
      context: .
      dockerfile: ./docker/nestjs-app.Dockerfile
      target: development
      args:
        NESTJS_APP: mobile-api-gateway
    ports:
      - '3001:80'
    env_file:
      - ./env/mobile-api-gateway.env
      - ./env/rabbitmq.env
    command: npm run start:dev mobile-api-gateway
    depends_on:
      - rabbitmq
    volumes:
        - .:/app
        - /app/node_modules



  users-microservice:
    build:
      context: .
      dockerfile: ./docker/nestjs-app.Dockerfile
      target: development
      args:
        NESTJS_APP: users-microservice
    env_file:
      - ./env/users-microservice.env
      - ./env/rabbitmq.env
    command: npm run start:dev users-microservice
    depends_on:
      - web-api-gateway
      - mobile-api-gateway
    volumes:
        - .:/app
        - /app/node_modules

  auth-microservice:
    build:
      context: .
      dockerfile: ./docker/nestjs-app.Dockerfile
      target: development
      args:
        NESTJS_APP: auth-microservice
    env_file:
      - ./env/auth-microservice.env
      - ./env/rabbitmq.env
    command: npm run start:dev auth-microservice
    depends_on:
      - web-api-gateway
      - mobile-api-gateway
    volumes:
        - .:/app
        - /app/node_modules

  notifications-microservice:
    build:
      context: .
      dockerfile: ./docker/nestjs-app.Dockerfile
      target: development
      args:
        NESTJS_APP: notifications-microservice
    env_file:
      - ./env/notifications-microservice.env
      - ./env/rabbitmq.env
    command: npm run start:dev notifications-microservice
    depends_on:
      - web-api-gateway
      - mobile-api-gateway
    volumes:
        - .:/app
        - /app/node_modules