export enum AuthMicroserviceMessages {
  AUTH_MS_PING = `AUTH_MS_PING`,

  VALIDATE_USER_LOGIN = `VALIDATE_USER_LOGIN`,
  CREATE_NEW_JWT = `CREATE_NEW_JWT`,
  CHECK_JWT = `CHECK_JWT`,
  REFRESH_JWT = `REFRESH_JWT`,
}

export enum AuthMicroserviceEvents {
  AUTH_MS_PINGED = `AUTH_MS_PINGED`,

  USER_LOGIN_VALIDATED = `USER_LOGIN_VALIDATED`,
}